// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vasbquvjiirnnflfctya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhc2JxdXZqaWlybm5mbGZjdHlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjE5MjYsImV4cCI6MjA2NjIzNzkyNn0.jsVguvda-KI8wwiTrB43bSyb8QDbFw-TeKPY4BAR9wA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);